### ISSUE TITLE
Width and escape changes fail to generate mandelbrot

### ISSUE THREAD

**Issue by snihar2** [snihar2/scalable_mandelbrot#5]
**Problem**
For some or most width values, mandelbrot generation doesn't work.

**Comment by G3ryon** [comment]
After some refactoring, the issue was in the duplication of a part of the client code. It is possible to generate for any width now. Attach an example with a width of 40.
![output12-22-2020T11-24-00](https://user-images.githubusercontent.com/36258619/102878500-a87c8900-4448-11eb-978c-548271ba0f0b.png)
